export default function Head() {
    return (
        <>
            <title>📚 Bookshelf</title>
            <meta
                content="width=device-width, initial-scale=1"
                name="viewport"
            />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="anonymous"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=K2D:wght@300;400;500;700&family=Playfair+Display:wght@600;700;900&display=swap"
                rel="stylesheet"
                precedence="default"
            />
        </>
    );
}
